// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_world_1_completed_with_3_stars_on_each_level = "CgkIrc3-7scEEAIQCg"; // <GPGSID>
        public const string achievement_world_3_completed_with_minimum_of_2_stars_on_each_level = "CgkIrc3-7scEEAIQCQ"; // <GPGSID>
        public const string achievement_world_1_completed_with_minimum_of_2_stars_on_each_level = "CgkIrc3-7scEEAIQBw"; // <GPGSID>
        public const string achievement_world_1_completed = "CgkIrc3-7scEEAIQBA"; // <GPGSID>
        public const string achievement_world_3_completed_with_3_stars_on_each_level = "CgkIrc3-7scEEAIQDA"; // <GPGSID>
        public const string leaderboard_world_2 = "CgkIrc3-7scEEAIQAg"; // <GPGSID>
        public const string leaderboard_world_1 = "CgkIrc3-7scEEAIQAQ"; // <GPGSID>
        public const string achievement_world_3_completed = "CgkIrc3-7scEEAIQBg"; // <GPGSID>
        public const string leaderboard_world_3 = "CgkIrc3-7scEEAIQAw"; // <GPGSID>
        public const string achievement_world_2_completed_with_minimum_of_2_stars_on_each_level = "CgkIrc3-7scEEAIQCA"; // <GPGSID>
        public const string achievement_world_2_completed_with_3_stars_on_each_level = "CgkIrc3-7scEEAIQCw"; // <GPGSID>
        public const string achievement_world_2_completed = "CgkIrc3-7scEEAIQBQ"; // <GPGSID>

}

